name: Automotive Test Framework CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Hardware platform to test'
        required: true
        default: 'mock_platform'
        type: choice
        options:
          - mock_platform
          - ecu_platform_a
          - ecu_platform_b
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - all

env:
  DOCKER_IMAGE: automotive-tests
  HARDWARE_PLATFORM: mock_platform

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Export Docker image
        run: |
          docker save ${{ env.DOCKER_IMAGE }}:latest -o /tmp/docker-image.tar
      
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/docker-image.tar
          retention-days: 1

  test-smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      
      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar
      
      - name: Run smoke tests
        run: |
          docker run --rm \
            -e HARDWARE_PLATFORM=mock_platform \
            -v ${{ github.workspace }}/reports:/app/reports \
            ${{ env.DOCKER_IMAGE }}:latest \
            -m smoke \
            --alluredir=/app/reports/allure-results \
            --junit-xml=/app/reports/junit-smoke.xml
      
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: reports/junit-smoke.xml
          check_name: Smoke Test Results
      
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-reports
          path: reports/
          retention-days: 30

  test-regression:
    name: Regression Tests
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'schedule'
    
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      
      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar
      
      - name: Run regression tests
        run: |
          docker run --rm \
            -e HARDWARE_PLATFORM=mock_platform \
            -v ${{ github.workspace }}/reports:/app/reports \
            ${{ env.DOCKER_IMAGE }}:latest \
            -m regression \
            --alluredir=/app/reports/allure-results \
            --junit-xml=/app/reports/junit-regression.xml
      
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: reports/junit-regression.xml
          check_name: Regression Test Results
      
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: regression-test-reports
          path: reports/
          retention-days: 30

  test-can-bus:
    name: CAN Bus Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      
      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar
      
      - name: Run CAN bus tests
        run: |
          docker run --rm \
            -e HARDWARE_PLATFORM=mock_platform \
            -v ${{ github.workspace }}/reports:/app/reports \
            ${{ env.DOCKER_IMAGE }}:latest \
            -m can_bus \
            --alluredir=/app/reports/allure-results \
            --junit-xml=/app/reports/junit-can.xml
      
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: can-bus-test-reports
          path: reports/
          retention-days: 30

  generate-allure-report:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: [test-smoke, test-regression, test-can-bus]
    if: always()
    
    steps:
      - name: Download all test reports
        uses: actions/download-artifact@v4
        with:
          pattern: '*-test-reports'
          path: reports/
          merge-multiple: true
      
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: reports/allure-results
          allure_history: allure-history
          keep_reports: 20
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          destination_dir: reports

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Run Black (formatting check)
        run: black --check framework/ tests/
        continue-on-error: true
      
      - name: Run Flake8 (linting)
        run: flake8 framework/ tests/ --max-line-length=100
        continue-on-error: true
      
      - name: Run MyPy (type checking)
        run: mypy framework/ --ignore-missing-imports
        continue-on-error: true
